- name: A very simple playbook
  hosts: all
  tasks:
    - name: Print effective user running tasks
      debug: var=ansible_user_id
    - name: Print kernel release info
      debug: var=ansible_facts['kernel']
    - name: Print hostname server
      debug: var=ansible_facts['nodename']
    - name: variable playbook test
      debug: var=ansible_facts['memory_mb']
